Repository indexa-git/l10n-dominicana, pull requests merged in 2018-02, with the labels that each got.

#11 Add dgii webservice and autocomple partner from vat idetification
  ncf_manager/models/dgii_ws.py
  ncf_manager/models/res.py
  ncf_manager/static/src/js/marcos.js
  ncf_manager/test/__init__.py
  ncf_manager/test/test_ncf_manager.py
  ncf_manager/views/res_view.xml
  requirements.txt
Labels: enhancement

#23 Feature/dgii autocomplete widget issue #20
  .gitignore
  ncf_manager/__init__.py
  ncf_manager/__manifest__.py
  ncf_manager/controllers/__init__.py
  ncf_manager/controllers/controllers.py
  ncf_manager/static/src/js/ncf_manager.js
  ncf_manager/static/src/lib/bootstrap-typeahead.js
  ncf_manager/static/src/xml/ncf_manager.xml
  ncf_manager/views/assets_backend.xml
  ncf_manager/views/res_view.xml
Labels: enhancement

#27 [REF] Change approach for NCF validation on invoices
  ncf_manager/models/account_invoice.py
Labels: P1, enhancement

#26 [FIX] Ensure name exist before going through the condition
  ncf_manager/models/res.py
Labels: bug
