Repository indexa-git/l10n-dominicana, pull requests merged in 2018-03, with the labels that each got.

#38 Feature/create invoices screen
  ncf_pos/i18n/es_DO.po
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/js/invoices.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/templates.xml
Labels: enhancement

#75 Turning readonly to vat and fiscal type (Ref: Resolve #66)
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: enhancement, ncf_pos, review

#82 Feature/#80 make pdf print optional
  ncf_pos/models/pos_config.py
  ncf_pos/static/src/js/models.js
  ncf_pos/views/pos_config.xml
Labels: review

#81 Feature/create refund screen (Resolve #70)
  README.md
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/pos_config.xml
  pos_orders/static/src/js/pos_orders.js
Labels: review

#88 [MERGE] Bug-fix main sequence errors & vat disappearance
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/views/res_view.xml
Labels: bug, review

#90 [FIX] Just require NCF configuration for invoices with NCF journals
  ncf_manager/models/account_move.py
  ncf_manager/models/ir_sequence.py
Labels: bug, review

#91 [MERGE] Add main missing definitions on Norma 07-18
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/views/account_view.xml
  ncf_manager/wizard/account_invoice_cancel.py
Labels: review

#47 [REL] First functional release with a complete workflow
  README.md
  ncf_manager/__manifest__.py
  ncf_manager/controllers/controllers.py
  ncf_manager/i18n/es_DO.po
  ncf_manager/models/__init__.py
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/models/account_move.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/models/res.py
  ncf_manager/static/src/js/ncf_manager.js
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/views/account_view.xml
  ncf_manager/views/assets_backend.xml
  ncf_manager/views/ir_sequence_view.xml
  ncf_manager/views/res_view.xml
  ncf_manager/wizard/account_invoice_cancel.py
  ncf_manager/wizard/account_invoice_refund.py
  ncf_manager/wizard/account_invoice_refund.xml
  ncf_pos/__manifest__.py
  ncf_pos/data/data.xml
  ncf_pos/i18n/es_DO.po
  ncf_pos/models/__init__.py
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/security/ir.model.access.csv
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/css/pos_orders.css
  ncf_pos/static/src/js/db.js
  ncf_pos/static/src/js/invoices.js
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/popups.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/js/ticket_format.js
  ncf_pos/static/src/libs/jquery-autocomplete-ui.css
  ncf_pos/static/src/xml/ncf_pos.xml
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/pos_config.xml
  ncf_pos/views/pos_config_view.xml
  ncf_pos/views/pos_sesion_view.xml
  ncf_pos/views/pos_view.xml
  ncf_pos/views/templates.xml
  pos_orders/static/src/js/pos_orders.js
Labels: invalid, review
