Repository indexa-git/l10n-dominicana, pull requests merged in 2018-04, with the labels that each got.

#96 [ADD] Internal invoice number to customer and supplier invoices
  ncf_manager/data/sequences.xml
  ncf_manager/models/account_invoice.py
  ncf_manager/models/account_move.py
  ncf_manager/views/account_invoice_view.xml
Labels: review

#97 [ADD] Validation to verify the journal is minor and assign it
  ncf_manager/models/account_invoice.py
Labels: review

#102 [FIX] Singleton partner error when user attemp to create an another c…
  ncf_manager/models/res.py
  ncf_manager/views/res_view.xml
Labels: review

#104 [ADD] Wizard allow an easy way to configure internal sequences
  ncf_manager/__manifest__.py
  ncf_manager/data/sequences.xml
  ncf_manager/models/account_invoice.py
  ncf_manager/wizard/__init__.py
  ncf_manager/wizard/update_internal_sequence_wizard.py
  ncf_manager/wizard/update_sequence_wizard_view.xml
Labels: enhancement, ncf_manager, review

#93 Complete the credit note on POS
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#110 [Add] Add the credit note button to the payment screen
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#111 [Add] Make new ticket layout
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/js/chrome.js
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/templates.xml
Labels: review

#107 [REL] Release Candidate 2.0 with full workflow (Backend & POS)
  ncf_manager/__init__.py
  ncf_manager/__manifest__.py
  ncf_manager/controllers/controllers.py
  ncf_manager/data/sequences.xml
  ncf_manager/models/__init__.py
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/models/account_move.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/models/res.py
  ncf_manager/models/res_currency.py
  ncf_manager/models/shop.py
  ncf_manager/test/__init__.py
  ncf_manager/test/test_ncf_manager.py
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/views/res_view.xml
  ncf_manager/wizard/__init__.py
  ncf_manager/wizard/account_invoice_cancel.py
  ncf_manager/wizard/account_invoice_refund.py
  ncf_manager/wizard/update_internal_sequence_wizard.py
  ncf_manager/wizard/update_rate_wizard.py
  ncf_manager/wizard/update_sequence_wizard_view.xml
  ncf_pos/__init__.py
  ncf_pos/__manifest__.py
  ncf_pos/models/__init__.py
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/js/chrome.js
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/templates.xml
  pos_order_return/__init__.py
  pos_order_return/__manifest__.py
  pos_order_return/models/__init__.py
  pos_order_return/models/pos_order_return.py
  pos_orders/__init__.py
  pos_orders/__manifest__.py
  pos_orders/models/__init__.py
  pos_orders/models/wk_orders.py
Labels: review

#114 [MERGE] master into 11.0 up to 4090aa55abd25af5c5d0cd57efc6b0aba827a97f
  ncf_manager/__init__.py
  ncf_manager/__manifest__.py
  ncf_manager/controllers/controllers.py
  ncf_manager/data/sequences.xml
  ncf_manager/models/__init__.py
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/models/account_move.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/models/res.py
  ncf_manager/models/res_currency.py
  ncf_manager/models/shop.py
  ncf_manager/test/__init__.py
  ncf_manager/test/test_ncf_manager.py
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/views/res_view.xml
  ncf_manager/wizard/__init__.py
  ncf_manager/wizard/account_invoice_cancel.py
  ncf_manager/wizard/account_invoice_refund.py
  ncf_manager/wizard/update_internal_sequence_wizard.py
  ncf_manager/wizard/update_rate_wizard.py
  ncf_manager/wizard/update_sequence_wizard_view.xml
  ncf_pos/__init__.py
  ncf_pos/__manifest__.py
  ncf_pos/models/__init__.py
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/css/ncf_pos.css
  ncf_pos/static/src/js/chrome.js
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/templates.xml
  pos_order_return/__init__.py
  pos_order_return/__manifest__.py
  pos_order_return/models/__init__.py
  pos_order_return/models/pos_order_return.py
  pos_orders/__init__.py
  pos_orders/__manifest__.py
  pos_orders/models/__init__.py
  pos_orders/models/wk_orders.py
Labels: review

#113 [Add] text input popup to payment screen
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#118 [FIX] fixed typo
  ncf_manager/models/res.py
Labels: review

#119 [MERGE] develop into master up to 5bcc17d249769f39c709c150621ed27536cb852b
  ncf_manager/models/res.py
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#120 [MERGE] master into 11.0 up to 5bcc17d249769f39c709c150621ed27536cb852b
  ncf_manager/models/res.py
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#129 In times if you expose related fields on form, odoo execute write met…
  ncf_manager/models/ir_sequence.py
Labels: review

#126 Adding vertical scrolling on invoices query screen
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#134 [FIX] Reconcile payment on pos order after creation
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/js/models.js
Labels: review

#142 Feature/marcos api tools
  ncf_manager/__init__.py
  ncf_manager/__manifest__.py
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/wizard/__init__.py
  ncf_manager/wizard/update_rate_wizard.py
  ncf_manager/wizard/update_rate_wizard_view.xml
Labels: review

#143 Feature/ncf invoice template
  ncf_invoice_template/__init__.py
  ncf_invoice_template/__manifest__.py
  ncf_invoice_template/data/report_paperformat.xml
  ncf_invoice_template/report/report_invoice.xml
  ncf_invoice_template/report/report_templates.xml
Labels: review

#145 Fix labels and add div name
  ncf_invoice_template/report/report_invoice.xml
Labels: review

#133 Avoid change payment amount with credit note
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#139 Hidden button All Invoices for invoice journal without ncf_control
  ncf_pos/static/src/js/invoices.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
Labels: review

#151 [REF] internal_sequence should not be copy... an index is usefull too
  ncf_manager/models/account_invoice.py
Labels: review

#150 [IMP] implemented invoice NCF expiration date close #140
  ncf_manager/models/account_invoice.py
  ncf_manager/views/account_invoice_view.xml
Labels: review

#152 [FIX] applied conditional computation and visibility
  ncf_manager/models/account_invoice.py
  ncf_manager/views/account_invoice_view.xml
Labels: review

#155 Fix conditional to validate model to assign company and sale fiscal type
  ncf_manager/models/res.py
Labels: review

#156 [MERGE] Stable changes from branch 'develop' into 'master'
  ncf_invoice_template/__init__.py
  ncf_invoice_template/__manifest__.py
  ncf_invoice_template/data/report_paperformat.xml
  ncf_invoice_template/report/report_invoice.xml
  ncf_invoice_template/report/report_templates.xml
  ncf_manager/__init__.py
  ncf_manager/__manifest__.py
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/models/res.py
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/views/account_view.xml
  ncf_manager/wizard/__init__.py
  ncf_manager/wizard/account_invoice_cancel.py
  ncf_manager/wizard/update_rate_wizard.py
  ncf_manager/wizard/update_rate_wizard_view.xml
  ncf_pos/__manifest__.py
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/js/chrome.js
  ncf_pos/static/src/js/invoices.js
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/pos_config.xml
  ncf_pos/views/pos_view.xml
Labels: review

#157 [REL] 11.0
  ncf_invoice_template/__init__.py
  ncf_invoice_template/__manifest__.py
  ncf_invoice_template/data/report_paperformat.xml
  ncf_invoice_template/report/report_invoice.xml
  ncf_invoice_template/report/report_templates.xml
  ncf_manager/__init__.py
  ncf_manager/__manifest__.py
  ncf_manager/models/account.py
  ncf_manager/models/account_invoice.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/models/res.py
  ncf_manager/views/account_invoice_view.xml
  ncf_manager/views/account_view.xml
  ncf_manager/wizard/__init__.py
  ncf_manager/wizard/account_invoice_cancel.py
  ncf_manager/wizard/update_rate_wizard.py
  ncf_manager/wizard/update_rate_wizard_view.xml
  ncf_pos/__manifest__.py
  ncf_pos/models/pos_config.py
  ncf_pos/models/pos_order.py
  ncf_pos/static/src/js/chrome.js
  ncf_pos/static/src/js/invoices.js
  ncf_pos/static/src/js/models.js
  ncf_pos/static/src/js/screens.js
  ncf_pos/static/src/xml/pos.xml
  ncf_pos/views/pos_view.xml
Labels: review

#158 [REF] refact template layout
  ncf_invoice_template/__manifest__.py
  ncf_invoice_template/data/report_paperformat.xml
  ncf_invoice_template/report/report_invoice.xml
  ncf_invoice_template/report/report_templates.xml
Labels: don't merge, review

#162 Backport modules Norma 06-2018
  ncf_invoice_template/__manifest__.py
  ncf_invoice_template/report/report_invoice.xml
  ncf_invoice_template/report/report_templates.xml
  ncf_manager/__manifest__.py
  ncf_manager/models/ir_sequence.py
  ncf_manager/models/res.py
  ncf_manager/views/account_view.xml
Labels: review

#165 [PORT] Adapt ncf_pos views to v10
  ncf_invoice_template/report/report_invoice.xml
  ncf_pos/models/pos_config.py
  ncf_pos/views/pos_config.xml
Labels: review
